In [20]:
import numpy as np
import pandas as pd
from matplotlib import cm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error, mean_absolute_error
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from scipy.stats import kstest, norm
from collections import Counter
df = pd.read_csv('data.csv')
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000,Master's Degree,Married,2,Owned,High
2,35,Female,75000,Doctorate,Married,1,Owned,High
3,40,Male,125000,High School Diploma,Single,0,Owned,High
4,45,Female,100000,Bachelor's Degree,Married,3,Owned,High

In [21]:
df['Credit Score'].unique()

<ArrowStringArray>
['High', 'Average', 'Low']
Length: 3, dtype: str

In [22]:
size_map = {'Female' : 0, 'Male' : 1}
df['Gender'] = df['Gender'].map(size_map)

size_map = {"Bachelor's Degree" : 0, "Master's Degree" : 1, "High School Diploma" : 2, "Associate's Degree" : 3, "Doctorate" : 4}
df['Education'] = df['Education'].map(size_map)

size_map = {'Single' : 0, 'Married' : 1}
df['Marital Status'] = df['Marital Status'].map(size_map)

size_map = {'Owned' : 0, 'Rented' : 1}
df['Home Ownership'] = df['Home Ownership'].map(size_map)

size_map = {'High' : 0, 'Average' : 1, 'Low' : 2}
df['Credit Score'] = df['Credit Score'].map(size_map)

In [23]:
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,0,50000,0,0,0,1,0
1,30,1,100000,1,1,2,0,0
2,35,0,75000,4,1,1,0,0
3,40,1,125000,2,0,0,0,0
4,45,0,100000,0,1,3,0,0

In [24]:
X = df.iloc[:,0:7]
y = df.iloc[:, 7]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, stratify = y)

In [26]:
param_grid = {
    'n_estimators' : [100, 150, 200, 300],
    'max_depth' : [1,3,5,7,10,15,18,21]
}

gscv = GridSearchCV(estimator = RandomForestClassifier(), param_grid = param_grid, cv = 5)
gscv.fit(X_train, y_train)
print(gscv.best_params_)
model = gscv.best_estimator_

{'max_depth': 15, 'n_estimators': 200}

In [27]:
print(gscv.best_score_)

0.9836666666666666